### ISSUE TITLE
Pls help me

### ISSUE THREAD

**Issue by Kaushal1119** [subroto-das/WiFucker#1]
┌─[KAUSHAL@termux]─[~/WiFucker]
└──╼ ❯❯❯ python3 WiFucker.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/WiFucker/WiFucker.py", line 9, in <module>
    commands=subprocess.check_output(["netsh", "wlan", "show", "profiles"]).decode('utf-8').split('\n')
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.10/subprocess.py", line 1840, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Error 2] No such file or directory: 'netsh' 

What to do pls tell me? @subroto-das

**Comment by subroto-das** [comment]
Hi there,
Thanks for asking help.

Actually, this tool is for Windows OS. Those commands only runs on Windows
Command Line (CMD). You are using termux, which is a Linux Terminal.
Windows Commands doesn't runs on Linux Command Line.
That's why you got an error.
You should use your Windows PC for run this tool....
I hope you understand...

বৃহস্পতি, ১০ ফেব, ২০২২ তারিখে ৯:৫৫ AM টায় তারিখে Kaushal1119 <
***@***.***> লিখেছেন:

**Comment by Kaushal1119** [comment]
Thanks for the explanation 🙂☺️
